POST http://localhost:1024/courses/createCourse
Content-Type: application/json

{
  "name": "Web security",
  "startDate": "2022-02-01",
  "endDate": "2022-04-30",
  "timeToMeet": "Mondays - s:13:00, e:14:00",
  "credits": 5,
  "capacity": 20
}

###

POST http://localhost:1024/courses/updateCourse
Content-Type: application/json

{
  "courseId": "62d10d1f1a036e2429ac6659",
  "startDate": "2022-05-01",
  "endDate": "2022-08-31",
  "timeToMeet": "Thursday - s:09:00, e:10:00",
  "capacity": 35
}

###

GET http://localhost:1024/courses/getAll
Accept: */*
Cache-Control: no-cache

###
